### ISSUE TITLE
Arduino Every

### ISSUE THREAD

**Issue by Cleanse22** [Freenove/Freenove_WS2812B_RGBLED_Controller#2]
I recently aquired an Arduino Every and I would like to use that to power my WS2812B RGB LED-strip. Sadly I get a bunch of errors whenever I try to compile the "Rainbow.ino" example. The error messages are included in [here](https://github.com/Freenove/Freenove_WS2812B_RGBLED_Controller/files/4801346/Error_rainbow.txt). If I can do anything to help please let me know.

**Comment by SuhaylZhao** [comment]
Hi,

The wire libraryin Arduino every is different from the wire library in Arduino uno, which leads to the compatibility problem of the controller library. We will fix these problems soon.

Thanks.

**Comment by Cleanse22** [comment]
Alright, thank you, do you have a suggestion for a quick fix that I can apply myself?

**Comment by SuhaylZhao** [comment]
Hi,

I am very sorry to reply you so late.

The code has been updated, please try it.

Thanks.

**Comment by Cleanse22** [comment]
No problem, I found a fix which worked. But thank you for putting in the effort!

I just tried compiling the code and it still gives the same errors. When I open my Library Manager of the Arduino IDE (version 1.8.13, WIN10, 64-bit) it does not show the library as updatable. Do I need to manually download and save the library from here or is there a delay before it's rolled out?

**Comment by SuhaylZhao** [comment]
Hi,

This is caused by the delay of update. The library of Arduino is updated every hour. You can download and install the update manually

Thanks.
